# Generated by Django 2.1.2 on 2018-10-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('block', models.CharField(max_length=50)),
                ('iucr', models.CharField(max_length=50)),
                ('primary_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('location_description', models.TextField()),
                ('arrest', models.BooleanField()),
                ('domestic', models.BooleanField()),
                ('beat', models.CharField(max_length=125)),
                ('district', models.CharField(max_length=125)),
                ('ward', models.CharField(max_length=125)),
                ('community_area', models.CharField(max_length=125)),
                ('fbi_code', models.CharField(max_length=125)),
                ('updated_on', models.DateTimeField(max_length=125)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
