# Generated by Django 2.1.2 on 2018-10-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimes',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimes',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
